version: '3'
services:
  db:
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: edwin
      MYSQL_PASSWORD: edwin
      MYSQL_DATABASE: edwin
    image: mariadb
  web:
    build: .
    ports:
      - '5555:5000'
    volumes:
      - .:/code
