version: '3'
services:
  db:
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: edwin
      MYSQL_PASSWORD: edwin
      MYSQL_DATABASE: edwin
    image: mariadb
  web:
    image: php-pdo
    ports:
      - "8002:80"
    volumes:
      - ./public:/var/www/html
